### ISSUE TITLE
Staging instance

### ISSUE THREAD

**Issue by jamiefolsom** [mit-history/rcf-ui#2]
Hi @adimasci,

I've attached the [mit-history/cfrp staging](http://staging-app.cfregisters.org) database to the [mit-history/rcf-ui staging](https://rcf-ui-staging.herokuapp.com/) application. You can see that at: https://dashboard.heroku.com/apps/rcf-ui-staging/resources

At the moment, deploy is broken on rcf-ui staging and production, I believe due to an issue with npm dependencies (see #1). Once that's resolved, we should be able to test the updated database with the application.

Let me know if I can help with that.

Thanks!

Jamie

**Comment by adimascio** [comment]
Hi Jamie,

Sorry, I'm not in Paris this week, hence my lack of responses. I've
restored the dependency on react-bootstrap-table and pushed it on the
master branch. Unfortunately, I won't be able to test this thoroughly
before tomorrow. Maybe you could at least try to deploy it on staging
tonight ?

Cheers,
Adrien

**Comment by jamiefolsom** [comment]
Hi @adimascio. No problem at all. I am happy to deploy it to staging. Probably first thing tomorrow morning. Thanks!

**Comment by adimascio** [comment]
The deployment seems OK now. Unfortunately, the links to the La Grange database seem broken but it probably has nothing to do with us.

**Comment by jamiefolsom** [comment]
Hi Adrien, 

I see that you re-deployed your application. Thanks for doing that. It's now returning a 404 error on load. Is that what you're seeing too?

I am going to let the team know about the broken Lagrange links, and see what they want to do about launching the site.

Thanks,

Jamie

**Comment by adimascio** [comment]
On which URL precisely ?

**Comment by jamiefolsom** [comment]
See: https://devcenter.heroku.com/articles/heroku-postgresql#connecting-in-node-js

**Comment by adimascio** [comment]
I thought it would deploy directly no ui.cfregisters.org

**Comment by jamiefolsom** [comment]
I set this staging instance of RCF-UI up to test the staging instance of the production database (http://staging-app.cfregisters.org), but it's fine to just use ui.cfregisters.org -- no problem. 

I will have to change the database that application is attached to, so that it uses the database from http://staging-app.cfregisters.org, to test it. 

Once we confirm it's working, I will update the production database (for http://app.cfregisters.org) and attach ui.cfregisters.org to that production database.

If that's ok with you, I can go ahead and do that.

**Comment by adimascio** [comment]
@jamiefolsom your other PR on ssl looks good to me, I've merged it. I pushed a few other modifications on staging.

Last but not least concern… the  "person_agg" materialized view is not set properly. Did you re-run the pgviews.sql script ?

**Comment by jamiefolsom** [comment]
I did, but I can do that again -- are there changes to that pgviews.sql file?

**Comment by jamiefolsom** [comment]
I've re-run the pgviews file, in case the views had changed. Let me know if that helps.

**Comment by jamiefolsom** [comment]
Ah, but maybe your changes to pgviews.sql is not in https://github.com/mit-history/cfrp#master?

**Comment by adimascio** [comment]
Still not good on https://rcf-ui-staging.herokuapp.com/ ("0 auteurs").

I've just downloaded a copy of cfrp-staging and "person_agg" is empty. Once pgviews.sql is run, everything seems fine again.

**Comment by adimascio** [comment]
I've not changed it in a while but the last version is always https://github.com/mit-history/rcf-ui/blob/master/pgviews.sql

**Comment by jamiefolsom** [comment]
Ok I will run that one again in a few minutes

**Comment by jamiefolsom** [comment]
OK, I ran the pgviews file from rcf-ui, and now things appear to be working!

http://rcf-ui-staging.herokuapp.com/genres

**Comment by jamiefolsom** [comment]
So am I correct that You've made changes which remove the La Grange data from this app? If so, and it's working otherwise, I think we can move ahead with launching the new site. Do you agree?

**Comment by adimascio** [comment]
@jamiefolsom I have simply deactivated the data fetching from La Grange. I also noticed that column id have (again ?) changed in the lagrange tables but since it's not used anymore for now, we can postpone this issue.

I've deployed a new version this morning on staging and it seems to run ok. Feel free to perform a quick check but otherwise, I think staging can be promoted to production !

**Comment by jamiefolsom** [comment]
Great! I didn't change the id columns or data in the tables -- I added columns to the join tables to store primary keys, and copied those keys into those tables. I kept the ext_id relations in place as well, so you can use either the ext_ids, or the primary keys; they establish the same correspondences. Having the primary keys use the standard naming convention simplifies the administrative interface. Let me know if that sounds OK to you.
